### ISSUE TITLE
Unable to list the Catalog Items available to any projects

### ISSUE THREAD

**Issue by chris-mcguinness** [Azure/deployment-environments#2]
Apologies if I'm creating this ticket in the wrong place.

As per the documentation I have setup an ADE environment with a catalog that is syncing correctly over both GIT and AzureDevOps.
https://learn.microsoft.com/en-us/azure/deployment-environments/quickstart-create-access-environments

However, I'm unable to List the catalog items for any project using the Azure CLI. The tooling is up to date.

As per the documentation, I have ran the following command:
```
#List the Catalog Items available to a specific project.
az devcenter dev catalog-item list --dev-center "{devCenterName}" --project-name "{projectName}" -o table

```

This simply returns "[]". Is there anything I may need to investigate?  

```

However, the below command works as intended and returns the correct number of environments. 
# list the type of environments you can create in a specific project.
az devcenter dev environment-type list --dev-center "{devCenterName}" --project-name "{projectName}" -o table
```

**Comment by j-rewerts** [comment]
Sorry for the delay @chris-mcguinness ! Could you share your dev center name? I'll use it to query our logs and see why the catalog items are failing to sync.

**Comment by j-rewerts** [comment]
Just wanted to ping this once more. @chris-mcguinness Any luck syncing that catalog?

**Comment by j-rewerts** [comment]
Closing, but feel free to reopen if you continue to have issues.
