### ISSUE TITLE
Enable Auto Expiration

### ISSUE THREAD

**Issue by KarsonAlford** [Azure/deployment-environments#24]
Where can I find documentation on enabling auto expiration and setting the expiration date?
Does this feature currently exists?
What is the timeline for adding this feature?

May 24 2022 this article mentions expirations and has a screenshot:
[https://techcommunity.microsoft.com/t5/azure-developer-community-blog/introducing-azure-deployment-environments/bc-p/3920365#M1066](https://techcommunity.microsoft.com/t5/azure-developer-community-blog/introducing-azure-deployment-environments/bc-p/3920365#M1066)

4 Months ago Scott Hanselman mentions setting expirations in his video here:
[https://www.youtube.com/watch?v=_rRiVELgdf4](https://www.youtube.com/watch?v=_rRiVELgdf4)
I can even have an expiration date to make sure that I don't accidentally keep a bunch of Azure resources around. I don't want to waste any money. They'll get deleted automatically when I'm done. With them we'll pick from a template. Notice here we've got different templates. I'm going to pick podcast A ...

3 months ago at Microsoft Build 2023:
[https://www.youtube.com/watch?v=yTC40g4oyck](https://www.youtube.com/watch?v=yTC40g4oyck)
We're also working on adding an auto expiry functionality, which will help the developer to define an auto expiry, and that will automatically delete the environment based on the configured date. In the second demo, we saw an automated operation where there was a streamlined deployment of ...

**Comment by sagarlankala** [comment]
Hi @KarsonAlford - Thanks for reaching out! We are currently working on enabling auto-delete functionality. ETA for public roll out - Nov 2023.

Do you mind elaborating on your scenario and user workflows that you are enabling using Azure Deployment Environments?

**Comment by KarsonAlford** [comment]
We want developers to be able to provision short lived VMs for testing.  We are creating the VMs with a daily shutdown required and want to include a clean up date when the resource group will be removed.

**Comment by ericaguthan** [comment]
The feature released in November, closing this issue
