### ISSUE TITLE
Removing Access to User

### ISSUE THREAD

**Issue by KarsonAlford** [Azure/deployment-environments#29]
A user that has created deployment environments appears to be the only one who can delete those environments.

When access was removed from a user their environments in Project\Environments were no longer displayed.

When the environments still exists but are not displayed in Project\Environments the option to delete the Project\EnvironmentType pairing becomes enabled.  Attempting to delete the pairing results in an error.  This is also true of the Project itself.  The delete button at the top of the Overview page is available but the delete will fail and a banner will appear on the Overview page stating that the resource is in a failed state.

Restoring the users access to try to resolve these issues does not appear to work.

**Comment by KarsonAlford** [comment]
It took a couple of weeks in October working with Microsoft to get these environments cleaned up.  We stopped using deployment environments because of this issue.

**Comment by sagarlankala** [comment]
Hi @KarsonAlford  - Sorry that you have faced this issue. 

There was a bug with deletion of environments and its fixed now. Additionally, apart from the creator of the environment, even the project admin is allowed to create an environment. We are also working on the capability to cascade delete environments when the project is deleted. 

I would like to connect with you to better understand your scenario and talk about the roadmap. Do you mind providing your availability for next week by sending an email to adesupport@microsoft.com?
