### ISSUE TITLE
Unable to create an environment (create-command returns "environment not found"-error)

### ISSUE THREAD

**Issue by hsirtl** [Azure/deployment-environments#3]
I was trying to set up a deployment environment following the [quickstart instructions](https://learn.microsoft.com/en-us/azure/deployment-environments/quickstart-create-access-environments). Everything works fine except the final step where I'm supposed to create the actual environment via the ```az devcenter dev environment create```-command.
Tools are updated (installed today).
As per the documentation, I have ran the following command (I replaced the variables {catalog} and {catalog-item}, of course):
```
az devcenter dev environment create `
    --dev-center-name devcenter `
    --project-name my-dev-project `
    --environment-name my-first-env `
    --environment-type Dev `
    --catalog-name {catalog} `
    --catalog-item-name {catalog-item}
```
The command fails with the error message
```
(EnvironmentNotFound) The environment resource was not found.
Code: EnvironmentNotFound
Message: The environment resource was not found.
```
Indeed, the environment ```my-first-env``` cannot be found. It doesn't exist, and I want to create it.

**Comment by j-rewerts** [comment]
Hi @hsirtl! Apologies for the strange error. This usually happens when the calling user doesn't have the correct permissions. [This](https://learn.microsoft.com/en-us/azure/deployment-environments/quickstart-create-and-configure-projects#give-project-access-to-the-development-team) part of the documentation covers assigning one of our data plane roles to your user. Please try assigning Deployments Environments User to your user and see if that helps.

**Comment by hsirtl** [comment]
Hi @j-rewerts,
thanks a lot for this hint. It actually solved the issue. However: my user has "Owner"-permissions on the subscription where everything resides, so I assumed that these permissions somehow "included" everything I needed for provisioning an environment. Maybe, this should be stated in the docs as well.
Best regards,
Holger

**Comment by j-rewerts** [comment]
Glad to hear it!

This will get into the nitty gritty a little bit, but Azure has the concept of management plane and data plane. Owner grants all management plane actions but doesn't grant any data plane actions. For Dev Center, both Project Admin and Deployments Environments User contain our data actions required to CRUD any Environment.

For what it's worth, the 404 we return has confused many people already and we're considering returning something a little more informative to help people out in this situation. We also are updating our docs with info on this error in case others run into it.
________________________________

**Comment by hsirtl** [comment]
Hi @j-rewerts,
thanks for the additional explanation. I think my confusion was caused by the fact that something that in other context in Azure is considered a management plane operation (i.e., provisioning infrastructure by running ARM-deployments) in case of Deployment Environments is a data plane operation. Conceptually, this makes sense (especially there is more involved than just the deployments themselves).
Best,
Holger
