### ISSUE TITLE
deploying environment using main.bicep due to InvalidContentLink

### ISSUE THREAD

**Issue by doruit** [Azure/deployment-environments#31]
Hi, i successfully used the sample web app from this repo (https://github.com/Azure/deployment-environments/tree/main/Environments/WebApp) to deploy using the following yaml:

```
name: WebApp-1
version: 1.0.0
summary: Azure Open AI Chatbot Web App Environment
description: Deploys an Azure Open AI Chatbot Web App without a data store
runner: ARM
templatePath: azuredeploy.json
```

From the documentation I understood that one could also point to a bicep file to deploy the environment so i changed the yaml to:

```
name: WebApp-1
version: 1.0.0
summary: Azure Open AI Chatbot Web App Environment
description: Deploys an Azure Open AI Chatbot Web App without a data store
runner: ARM
templatePath: main.bicep
```

I tried deploying the environment with and without having the associated azuredeploy.json file in the same folder. 

My question are: 
Is build-arm.py used at some step of the process or not? 
Would it suffice to only have a bicep template and yaml manifest file in the environment folder or does it require the azuredeploy.json ARM template next to it? 

When pointing to the bicep template i get this error: 

```
InvalidArmTemplate
The template file provided failed deployment validation (Code: InvalidContentLink,  Message: Unable to download deployment content from **'https://lyd087dnw8ner705.blob.core.windows.net**/templates/project-genai.simpleaichatbot.133426215507879710/02-AzureAIDemo-A-SimpleChatbot/Environment/WebChatbot1/main.bicep?skoid=0efc828b-fa51-4535-913d-a277c19e5e05&sktid=33e01921-4d64-4f8c-a055-5bdaffd5e33d&skt=2023-10-24T11%3A30%3A51Z&ske=2023-10-25T11%3A45%3A51Z&sks=b&skv=2021-08-06&sv=2021-08-06&st=2023-10-24T11%3A30%3A51Z&se=2023-10-25T11%3A45%3A51Z&sr=c&sp=rl&sig=*Sanitized Azure Storage Account Shared Access Signature*'. The tracking Id is 'e282487d-db60-456d-9804-30525bbe8a53'. Please see https://aka.ms/arm-deploy-resources for usage details.).
```

Thanks in advance !!!

**Comment by ericaguthan** [comment]
Hi @doruit ,

Currently we do not natively support bicep deployments, and they will need to be compiled to ARM to deploy. This feature will be coming soon, so keep an eye out for blog posts to get more specific timeline information once that is available

**Comment by ericaguthan** [comment]
Hi @doruit ,

If you would like to start experimenting with native bicep support in ADE, we can onboard you to the private preview of this feature. Please reach out to adesupport@microsoft.com for more information on how to get started!

**Comment by doruit** [comment]
Hi @ericaguthan, thanks for your reply. That would be great. I will send an email with the details of our subscription. 
Thanks
