### ISSUE TITLE
Is there any guidance to use terraform IaC Codes with AzureDeployment environment ?

### ISSUE THREAD

**Issue by vivuu1989** [Azure/deployment-environments#36]
We were trying for  the GitOps flow for our developers  with ADE, so that we can make use of our existing terraform codes with GitOps method using AzureDevops Repos as catalogs repo. We followe the MS documents and which is not stating anything about how to use or configure terraform IaC codes with the AzureDeployment Environment.

**Comment by ericaguthan** [comment]
Hi @vivuu1989 

Terraform support is currently in private preview, as is Bicep Support. You must be registered with the preview for these features to work, and details on how to consume these features are provided as part of the preview onboarding process. If you are interested in signing up, please contact adesupport@microsoft.com for further guidance on getting onboarded.
