### ISSUE TITLE
[Developer Portal] How many parameters can an environment have?

### ISSUE THREAD

**Issue by nhvduy** [Azure/deployment-environments#7]
Hi Team,

When creating environment with parameter inputed from developer portal, the provisioning task finish with 4 parameters. When I add 1 more (5 params) I always get error message and not know what the rootcause is.
![image](https://user-images.githubusercontent.com/35753346/224890828-5b7d2216-e19d-4a74-9e58-de70cc28f683.png)

I think it can be the limitation of allowing only 4 parameters. there is no error if I use Azure CLI.

Thanks

**Comment by nhvduy** [comment]
Hi @j-rewerts 

Thanks for your promptly response. I tried with more simple ARM template and I could make it work. I told my co-worker to double check his template and we found out an interesting thing. 
If we specify a parameter in manifest file as Required and that parameter has default value, then in devportal we have to change its value unless we get the error message.
Please close this issue.
Thanks

**Comment by j-rewerts** [comment]
Ah yes, default and required don't work well together at all right now. We're considering blocking creation of catalog items that have params defined that are required and default.
